# Generated by Django 5.0 on 2024-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='Islamiyahtech Bank', max_length=100),
        ),
    ]
